Oda/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # 예시 : blog/
    path('', views.PostLV.as_view(), name='index'),

    # 예시 : blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 예시 : blog/post/django-example/슬러그-슬러그-슬러그
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name = 'post_detail'),

    # 예시 : blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # 예시 : blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 예시 : blog/archive/2022/9월
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 예시 : blog/archive/2022/9월/16/
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),

    # 예시 : blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),


    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

Oda/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import BookmarkLV, BookmarkDV
from mysite import views
from django.conf.urls.static import static
from django.conf import settings
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done', views.UserCreateDoneTV.as_view(), name='register_done'),

    # shkim
    path('', views.HomeView.as_view(), name='home'), # 추가

    path('bookmbark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('market/', include('market.urls')),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Oda/blog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.text import slugify
from photo.fields import ThumbnailImageField



# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="OWNER", blank=True, null=True)
    image = ThumbnailImageField(upload_to='post/%Y/%m',  blank=True, null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=(self.slug,))
    
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    
    def get_next(self):
        return self.get_next_by_modify_dt()

    def save(self, *arg, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*arg, **kwargs)

Oda/blog/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

Oda/blog/views.py
from audioop import reverse
from django.shortcuts import render
from django.views.generic import *
from django.views.generic.dates import *
from blog.models import Post
from django.conf import settings

from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


# Create your views here.

#-- ListView
class PostLV(ListView):
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 6

#-- DetailView
class PostDV(DetailView):
    model = Post

#-- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_dt'
    make_object_list = True
    # month_format = '%d' # 디폴트 값

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'

class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_dt'
    month_format = '%m'

class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    model = Post
    template_name = 'taggit/taggit_post_list.html'

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

#-- FormView
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord) | 
                                        Q(description__icontains=searchWord) |
                                        Q(content__icontains=searchWord)).distinct()
        context = { 'form' : form, 
                    'search_term' : searchWord,
                    'object_list' : post_list
                }
        # context = {}
        # context['form'] = form
        # context['search_term'] = searchWord
        # context['objet_list'] = post_list

        return render(self.request, self.template_name, context)

# LoginRequiredMixin -> 로그인한 사용자가 아니면 로그인 페이지로 이동
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    # fields = ['title', 'slug', 'description', 'content', 'tags']
    # initial = {'slug' : '자동으로-완성되니-적지마세요'}
    fields = ['title', 'description', 'content', 'tags', 'image']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

# LoginRequiredMixin -> 로그인한 사용자가 아니면 로그인 페이지로 이동
# object_list -> 현재 로그인한 사용자가 작성한 Post
class PostChangeLV(LoginRequiredMixin, ListView):
    template_name = 'blog/post_change_list.html'

    def get_queryset(self):
        return Post.objects.filter(owner = self.request.user)

# OwnerOnlyMixin -> 작성자만이 수정할 수 있도록
class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    # fields = ['title', 'slug', 'description', 'content', 'tags']
    fields = ['title', 'description', 'content', 'tags', 'image']
    success_url = reverse_lazy('blog:index')

# OwnerOnlyMixin -> 작성자만이 삭제할 수 있도록
class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

Oda/blog/templates/blog/post_all.html
{% extends 'base.html' %}

{% block title %}Movie{% endblock %}

{% block extra-style %}
<style>
    .w-btn-neon2 {
        position: relative;
        border: none;
        min-width: 200px;
        min-height: 50px;
        background: linear-gradient(
            90deg,
            rgba(129, 230, 217, 1) 0%,
            rgba(79, 209, 197, 1) 100%
        );
        border-radius: 1000px;
        color: darkslategray;
        cursor: pointer;
        box-shadow: 12px 12px 24px rgba(79, 209, 197, 0.64);
        font-weight: 700;
        transition: 0.3s;
    }

    .w-btn-neon2:hover {
        transform: scale(1.2);
        text-decoration-line: none;
    }

    .w-btn-neon2:hover::after {
        content: "";
        width: 30px;
        height: 30px;
        border-radius: 100%;
        border: 6px solid #00ffcb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }
    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        text-decoration-line: none;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
        border-radius: 4%;
    }
    .img_link:hover img {
        transition-duration: 0.7s;
        border-radius: 4% 4% 0 0;
    }
    .card-body:hover {
        color: blueviolet;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1> &#128253; Movie</h1>
    <br>
    <div class="row">
    {% for post in posts %}
    <div class="col-4">
        <div class="card">
            <a class="img_link" href="{{ post.get_absolute_url }}">
            <img src="{{ post.image.url }}" alt="" class="card-img-top" />
            <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h3>
                <!-- {{ post.modify_dt|date:"N d, Y" }} -->
                <p class="card-text">{{ post.description }}</p>
            </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div>
    <br>

    <div>
        <span>
            <h4>page {{ page_obj.number }} &#128450; </h4><br>
                {% if page_obj.has_previous %}
                <a class="w-btn-neon2 p-3 px-5" href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
                {% endif %}
    
                
    
                {% if page_obj.has_next %}
                <a class="w-btn-neon2 p-3 px-5" href="?page={{ page_obj.next_page_number }}">NextPage</a>
                {% endif %}
        </span>
    </div>
    
</div>

{% endblock %}

Oda/blog/templates/blog/post_archive.html
{% extends 'base.html' %}

{% block title %}post_achive.html{% endblock %}

{% block extra-style %}
<style>
    .w-btn-neon2 {
        padding-top: 7.5px;
        display: inline-block;
        position: relative;
        border: none;
        min-width: 80px;
        min-height: 50px;
        background: linear-gradient(90deg,
                rgba(129, 230, 217, 1) 0%,
                rgba(79, 209, 197, 1) 100%);
        border-radius: 1000px;
        color: darkslategray;
        cursor: pointer;
        box-shadow: 10px 8px 22px rgba(79, 209, 197, 0.64);
        font-weight: 700;
        transition: 0.3s;
        font-size: 20px;
        text-align: center;

    }

    .w-btn-neon2:hover {
        transform: scale(1.2);
        text-decoration-line: none;
    }

    .w-btn-neon2:hover::after {
        content: "";
        width: 30px;
        height: 30px;
        border-radius: 100%;
        border: 6px solid #00ffcb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }

    .list_date {
        list-style: none;
    }

    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        text-decoration-line: none;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
        border-radius: 4%;
    }
    .img_link:hover img {
        transition-duration: 0.7s;
        border-radius: 4% 4% 0 0;
    }
    .card-body:hover {
        color: blueviolet;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h3>{% now "N d, Y" %}</h3>
    <h1> &nbsp; Post &#128194; </h1> <br>

    <div>
        <ul>
            {% for date in date_list %}
            <li style="display:inline;">
                <a class="w-btn-neon2" href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                    {{ date|date:"Y" }}
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>

    <br />

    <div>
        <div class="row">
            {% for post in object_list %}
            <div class="col-4">
                <div class="card">
                    <a class="img_link" href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="" class="card-img-top" />
                        <div class="card-body">
                            <h3 class="card-title">{{ post.title }}</h3>

                            <p class="card-text">{{ post.description }}</p>

                            post - {{ post.modify_dt|date:"N d, Y" }}
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

<!-- <li class="list_date">{{ post.modify_dt|date:"Y년 m월 d일" }}&nbsp;&nbsp;&nbsp;
    <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong>
        {{ date|date:"Y" }}
    </a>
</li> -->
<!-- <div class="row">
    {% for post in posts %}
    <div class="col-4">
        <div class="card">
            <a class="img_link" href="{{ post.get_absolute_url }}">
            <img src="{{ post.image.url }}" alt="" class="card-img-top" />
            <div class="card-body">
                <h3 class="card-title">{{ post.title }}</h3>
                {{ post.modify_dt|date:"N d, Y" }}
                <p class="card-text">{{ post.description }}</p>
            </div>
            </a>
        </div>
    </div>
    {% endfor %}
</div> -->



<!-- <ul>
        {% for date in date_list %}
        <li style="display:inline;">
            <a class="w-btn-neon2" href="{% url 'blog:post_year_archive' date|date:'Y' %}">
                {{ date|date:"Y" }}
            </a>
        </li>
        {% endfor %}
    </ul>

    <br />
    
    <div class="row">
        {% for post in posts %}
        <div class="col-4">
            <div class="card">
                <a class="img_link" href="{{ post.get_absolute_url }}">
                <img src="{{ post.image.url }}" alt="" class="card-img-top" />
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    {{ post.modify_dt|date:"N d, Y" }}
                    <p class="card-text">{{ post.description }}</p>
                </div>
                </a>
            </div>
        </div>
        {% endfor %}
    </div> -->

Oda/blog/templates/blog/post_archive_day.html
{% extends 'base.html' %}

{% block title %}post_archive_day.html{% endblock %}

{% block content %}
<div class="container">
<h1>Post Archives for {{ day|date:"N d, Y"}}</h1>

    <div>
        <ul>
            {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d"}}&nbsp;&nbsp;
                <a href="{{post.get_absolute_url}}"><strong>{{post.title}}</strong></a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

Oda/blog/templates/blog/post_archive_month.html
{% extends 'base.html' %}

{% block title %}post_archive_month.html{% endblock %}

{% block extra-style %}
<style>
    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        text-decoration-line: none;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
        border-radius: 4%;
    }
    .img_link:hover img {
        transition-duration: 0.7s;
        border-radius: 4% 4% 0 0;
    }
    .card-body:hover {
        color: blueviolet;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1>Post for {{ month|date:"N, Y"}} &#127916; </h1>
    <br>

    <h3>movie of the month</h3>

    <br>
    <div>
        <div class="row">
            {% for post in object_list %}
            <div class="col-4">
                <div class="card">
                    <a class="img_link" href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="" class="card-img-top" />
                        <div class="card-body">
                            <h3 class="card-title">{{ post.title }}</h3>

                            <p class="card-text">{{ post.description }}</p>

                            post - {{ post.modify_dt|date:"N d, Y" }}
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Oda/blog/templates/blog/post_archive_year.html
{% extends 'base.html' %}

{% block title %}post_acrvhive_year.html{% endblock %}

{% block extra-style %}
<style>
    .w-btn-neon2 {
        padding-top: 7.5px;
        display: inline-block;
        position: relative;
        border: none;
        min-width: 80px;
        min-height: 50px;
        background: linear-gradient(90deg,
                rgba(129, 230, 217, 1) 0%,
                rgba(79, 209, 197, 1) 100%);
        border-radius: 1000px;
        color: darkslategray;
        cursor: pointer;
        box-shadow: 10px 8px 22px rgba(79, 209, 197, 0.64);
        font-weight: 700;
        transition: 0.3s;
        font-size: 20px;
        text-align: center;

    }

    .w-btn-neon2:hover {
        transform: scale(1.2);
        text-decoration-line: none;
    }

    .w-btn-neon2:hover::after {
        content: "";
        width: 30px;
        height: 30px;
        border-radius: 100%;
        border: 6px solid #00ffcb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }

    .list_date {
        list-style: none;

    }

    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        text-decoration-line: none;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
        border-radius: 4%;
    }
    .img_link:hover img {
        transition-duration: 0.7s;
        border-radius: 4% 4% 0 0;
    }
    .card-body:hover {
        color: blueviolet;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <h1> Post for {{ year|date:"Y"}} &#128197; </h1><br>

    <ul>
        {% for date in date_list %}
        <li style="display: inline;">
            <a class="w-btn-neon2" href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'m' %}">
                {{ date|date:"b" }}
            </a>
        </li>
        {% endfor %}
    </ul>
    <br />

    <div>
        <div class="row">
            {% for post in object_list %}
            <div class="col-4">
                <div class="card">
                    <a class="img_link" href="{{ post.get_absolute_url }}">
                        <img src="{{ post.image.url }}" alt="" class="card-img-top" />
                        <div class="card-body">
                            <h3 class="card-title">{{ post.title }}</h3>

                            <p class="card-text">{{ post.description }}</p>

                            post - {{ post.modify_dt|date:"N d, Y" }}
                        </div>
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

</div>

{% endblock %}

Oda/blog/templates/blog/post_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Post Change List Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Post Change - {{ user }}</h1>
    <br>

    <table class="table table-bordered table-sm table-striped">

        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'blog:update' item.id %}">Update</a></td>
                <td><a href="{% url 'blog:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Post Delete Confirm Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Post Delete</h1>
    <br>

    <form method="post">{% csrf_token %}
        <p>"{{ object }}" 게시물을 진짜 지우시겠습니까? 되돌릴 수 없습니다.</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}post_detail.html{% endblock %}

{% block extra-style %}
<style>
    h2 {
        font-weight: bold;
        padding: 5px 10px;
        /*  상자내무 간격 : 위아래 5px, 오른쪽왼쪽 15px  */
        border-bottom:1px solid #0066ff;
        /*  밑줄 라인 색상,굵기,선종류 설정가능  */
        border-left:8px solid #1093ff;
        /*  왼쪽 라인 색상,굵기,선종류 설정가능  */
    }

</style>
{% endblock %}

{% block content %}
<div class="container">
    <h2> &#127803; {{ post.title }} &#127803; </h2>
    <p>{{ post.modify_dt|date:"j F Y" }}</p>

    <p>
        {% if post.get_previous %}
        <a href="{{ post.get_previous.get_absolute_url }}" title="View previous post">
            &laquo;-- {{ post.get_previous }}
        </a>
        {% endif %}

        {% if post.get_next %}
        | <a href="{{ post.get_next.get_absolute_url }}" title="View next post">
            {{ post.get_next }}-- &laquo;
        </a>
        {% endif %}
    </p>

<!-- <div class="poster_description"> </div> -->
<div class="poster">
    <img src="{{ post.image.url }}" alt="" height="650" width="500">
</div>
    <br>
    
    <div class="body">
        {{ post.content|linebreaks }}
    </div>
    <br>

    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}

        <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        &emsp;

        <a href="{% url 'blog:tag_cloud' %}"> <span class='btn btn-info btn-sm'>TagCloud</span></a>
    </div>
    <div id="disqus_thread"></div>
</div>
{% endblock %}

{% block extra-script %}
<script>
    /**
    *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
    *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
    /*
    var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://django-oda.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by
        Disqus.</a></noscript>

{% endblock %}

Oda/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Post Form Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Post Create/Update - {{user}}</h1>
    <p class="font-italic">게시물을 생성하거나 수정을 할 수 있습니다.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3"> {% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <!-- <div class="form-group row">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.slug|add_class:"form-control"|attr:"readonly" }}
            </div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div> -->

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.description.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.content|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.tags|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.tags.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->