Oda/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # 예시 : blog/
    path('', views.PostLV.as_view(), name='index'),

    # 예시 : blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 예시 : blog/post/django-example/슬러그-슬러그-슬러그
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name = 'post_detail'),

    # 예시 : blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # 예시 : blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 예시 : blog/archive/2022/9월
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 예시 : blog/archive/2022/9월/16/
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),

    # 예시 : blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),


    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

Oda/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
    
]

Oda/market/urls.py
from django.contrib import admin
from django.urls import path
from market import views


app_name = 'market'
urlpatterns =[

    path('', views.MarketLV.as_view(), name='index'),

    path('cate/<int:cate>/', views.MarketCate, name='market_cate_list'),

    path('<int:pk>/', views.MarketDV.as_view(), name='market_detail'),
]

Oda/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import BookmarkLV, BookmarkDV
from mysite import views
from django.conf.urls.static import static
from django.conf import settings
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done', views.UserCreateDoneTV.as_view(), name='register_done'),

    # shkim
    path('', views.HomeView.as_view(), name='home'), # 추가

    path('bookmbark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('market/', include('market.urls')),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Oda/photo/urls.py
from django.urls import path
from photo import views


app_name = 'photo'
urlpatterns =[
     #Example:/photo/
    path('', views.AlbumLV.as_view(), name='index'),

    #Example:/photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    #Example:/photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    #Example:/photo/album/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

Oda/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        장고
        {% endblock %}
    </title>
    <!-- Bootstrap CSS only -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">

    {% block extra-style %}
    {% endblock %}
</head>

<body style="padding: top 90px;" id="top_">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic"> &#127805; Studio Ghibli</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-2 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
                </li>
                <!-- <li class="nav-item mx-2 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
                </li> -->
                <li class="nav-item mx-2 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'blog:index' %}">Movie</a>
                </li>
                <li class="nav-item mx-2 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
                </li>
                <li class="nav-item mx-2 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'market:index' %}">Market</a>
                </li>


                <li class="nav-item dropdown mx-2 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <!-- <a class="dropdown-item" href="{% url 'bookmark:add' %}">bookmark</a> -->
                        <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
                    </div>
                </li>

                <li class="nav-item dropdown mx-2 btn">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <!-- <a class="dropdown-item" href="{% url 'bookmark:change' %}">bookmark</a> -->
                        <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
                        <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
                    </div>
                </li>

                </li>
                <li class="nav-item dropdown mx-2 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Dropdown</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">admin</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                        <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
                    </div>
                </li>
               
            </ul>

            <!-- Search -->
            <!-- <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="search" name="search_word">
                <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
            </form> -->

            <!-- 회원(로그인/로그아웃/회원가입/비밀번호 변경) Start -->
        <ul class="navbar-nav mx-5">
            <li class="nav-item dropdown mx-2 btn btn-primary">
                {% if user.is_active %} <!-- 로그인된 상태라면 -->
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    로그인 / 회원가입
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>
        <!-- 회원(로그인/로그아웃/회원가입/비밀번호 변경) End -->
        </div>
    </nav>
    <div class="my-5" style="min-height:85vh;">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="fixed-bottom bg-info">
        <div class="text-white font-italic text-right mr-5">o-da &#127928; studio ghibli</div>
    </footer>    
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<script src="https://kit.fontawesome.com/fa34281664.js" crossorigin="anonymous"></script>
    {% block extra-script %}
    {% endblock %}

</html>

Oda/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}스튜디오 지브리{% endblock %}

{% block extra-style %}
<style type="text/css">
    .home-image {
        background-image: url("{% static 'img/gi.png' %}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: cover; 
        /* 120% */
        height: 700px;
        /* width: 100vw; */
        border-top: 1rem solid white;
        border-bottom: 10px soid #ccc;
        /* padding: 15px 0 0 20px; */
    }
    .title {
        color: #c80;
        font-weight:bold;
    }
    .powered {
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        text-decoration-line: none;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
    }
</style>
{% endblock %}

{% block content %}
    <div class="home-image">
        <!-- <h1 class="title">
            Studio Ghibli 
        </h/> -->
        <h4 class="powered">
            {% comment %} <i class="fas fa-arrow-circle-right"></i> {% endcomment %}
             {% comment %} powered by django and bootstrap. {% endcomment %}
        </h4>
    </div>

    <hr style="margin: 10px 0;">
<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3> &#128161; Studio Ghibli &#128161; </h3>
            <p>정식 명칭 : 株式会社スタジオジブリ <br>
                영어 : <span style="background-color:#fffd95">Studio Ghibli Inc.</span><br>
                한글 : 주식회사 스튜디오 지브리<br>
                국가 : 일본<br>
                업종 : 애니메이션 영화 기획 및 제작업<br>
                제작사 : 톱 크래프트 스튜디오<br>
                설립일 : 1985년 6월 15일<br>
                설립자 : 미야자키 하야오, 타카하타 이사오, 스즈키 토시오<br>
                대표자 : 호시노 코지 (대표이사 회장 겸 사장), 스즈키 토시오 (대표이사 프로듀서)<br>
                직원수 : 280명 (2021년 기준)<br>
                본사 : 도쿄도 코가네이시 카지노쵸 1초메 4-25<br>
            </p>
        </div>
        <div class="col-sm-6">
            <a href="https://www.ghibli.jp/">
                <img src="static/img/cha.jpg" width="540px" height="340px"  class="img_link">
            </a>
        </div>
    </div>
</div>
{% endblock %}

Oda/templates/template.html
{% extends 'base.html'%}

<!-- 제목 블럭 Start (기본값 My Blog Page) -->
{% block title %}
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록  Start -->
{% block extra-style%}

{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}

{% endblock %}
<!-- 콘텐츠 블록 End -->