Oda/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # 예시 : blog/
    path('', views.PostLV.as_view(), name='index'),

    # 예시 : blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 예시 : blog/post/django-example/슬러그-슬러그-슬러그
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name = 'post_detail'),

    # 예시 : blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # 예시 : blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 예시 : blog/archive/2022/9월
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 예시 : blog/archive/2022/9월/16/
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),

    # 예시 : blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),


    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

Oda/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import BookmarkLV, BookmarkDV
from mysite import views
from django.conf.urls.static import static
from django.conf import settings
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done', views.UserCreateDoneTV.as_view(), name='register_done'),

    # shkim
    path('', views.HomeView.as_view(), name='home'), # 추가

    path('bookmbark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('market/', include('market.urls')),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Oda/photo/urls.py
from django.urls import path
from photo import views


app_name = 'photo'
urlpatterns =[
     #Example:/photo/
    path('', views.AlbumLV.as_view(), name='index'),

    #Example:/photo/album/, same as /photo/
    path('album', views.AlbumLV.as_view(), name='album_list'),

    #Example:/photo/album/99/
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),

    #Example:/photo/album/99/
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    path('album/add/', views.AlbumCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    path('album/<int:pk>/update/', views.AlbumUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),
    
    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),
    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),
]

Oda/photo/models.py
from django.db import models
from django.urls import reverse
from photo.fields import ThumbnailImageField

# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField('One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey('auth.User', on_delete = models.CASCADE, verbose_name="OWNER", blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))
        # path('??/'<int:id>', ViewName.as_view(), name='album_detail')

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField('Upload Date', auto_now_add=True)
    owner = models.ForeignKey('auth.User', on_delete = models.CASCADE, verbose_name="OWNER", blank=True, null=True)

    class Meta:
        ordering = ('title',)
         
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

Oda/photo/forms.py
from django.forms import inlineformset_factory
from .models import *

PhotoInlineFormSet = inlineformset_factory(Album,
                                            Photo,
                                            fields = ['image','title','description'],
                                            extra = 2
                                            )

Oda/photo/views.py
from urllib import request
from django.shortcuts import render
from django.views.generic import *
from .models import Album, Photo

from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy

from .models import Album, Photo
from .forms import PhotoInlineFormSet
from mysite.views import OwnerOnlyMixin


# Create your views here.

class AlbumLV(ListView):
    model = Album

class AlbumDV(DetailView):
    model = Album

class PhotoDV(DetailView):
    model = Photo

class AlbumCV(LoginRequiredMixin, CreateView):
    model=Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid() :
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner = self.request.user)

class AlbumUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(self.request.POST, self.request.FILES, instance=self.object)
        else :
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context
    
    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else :
            return self.render_to_response(self.get_context_data(form=form))


class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url =reverse_lazy('photo:index')

class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PhotoChangeLV(LoginRequiredMixin, ListView):
   template_name = 'photo/photo_change_list.html'
   
   def get_queryset(self):
    return Photo.objects.filter(owner=self.request.user)


class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')

Oda/photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Album Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
    <br>
    
    <form method="post">{% csrf_token %}
        <p>앨범 "{{ object }}"을/를 삭제하면, 그 안의 모든 사진들도 삭제됩니다. 동의하십니까?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/photo/templates/photo/album_detail.html
{% extends 'base.html'%}

<!-- 제목 블럭 Start (기본값 My Blog Page) -->
{% block title %}
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록  Start -->
{% block extra-style%}

{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}

{% endblock %}
<!-- 콘텐츠 블록 End -->

Oda/photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Album Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
<h1>Album-Photo Create/Update - {{user}}</h1>
<p class="font-italic">PhotoInlineFormSet을 이용한 추가, 수정 폼 화면입니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if formset.errors %}
<div class="alert alert-warning">
    <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
    {% for formerrors in formset.errors %}
    {{ formerrors }}
    {% endfor %}
</div>
{% endif %}

{% if form.is_multipart or formset.is_multipart %}
<form enctype="multipart/form-data" action="" method="post">
    {% else %}
    <form action="." method="post">
        {% endif %}
        {% csrf_token %}

        <h4>앨범을 추가하거나 수정하세요</h4>

        <fieldset class="card pt-3">

            <div class="form-group row">
                {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.description|add_class:"form-control" }}
                </div>
            </div>

        </fieldset>

        <br>

        <h4>사진을 추가하거나 수정하세요.</h4>

        <fieldset class="card pt-3">

            {{ formset.management_form }}
            {% for form in formset %}
            {{ form.id }}
            {# form.album #}
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>

            <hr>
            {% endfor %}

        </fieldset>

        <div class="form-group card py-1">
            <div class="offset-sm-3 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/photo/templates/photo/album_list.html
{% extends 'base.html'%}

<!-- 제목 블럭 Start (기본값 My Blog Page) -->
{% block title %}
Album_Photo
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록  Start -->
{% block extra-style%}
<style>
    .title {
        color: rgb(54, 48, 59);
        border-style: outset;
        border-width: 5px;
        border-radius: 10px;
        padding-top: 10px;

    }

    /* .thumbnail {
            border: 3px solid rgb(251, 187, 9);
        } */

    .album_title_list ul {
        margin: 0px 0 0;
        padding: 0;
    }

    .album_title_list ul {
        display: inline-block;
        width: 100%;
        padding: 0 20px 0 20px;
        /* font-size: 0; */
    }

    .album_title_list {
        padding: 0;
        border: 0;
        text-align: center;
    }

    /* button */

    .album_title_list ul li a {
        border: 1px solid #eeeeee;
        line-height: 20px;
        padding: 3px 10px;
        /* color: white; */
        background-color: #F4D03F;

    }

    .album_title_list li a {
        display: block;
        padding: 10px 10px 10px 10px;
        color: #414141;
        border-radius: 100px;
    }

    .album_title_list li {
        text-decoration: none;

        display: inline-block;
        width: 20%;
        font-size: 14px;
        text-align: center;
        vertical-align: middle;
    }

    .w-btn-neon2 {
        display: inline-block;
        position: relative;
        border: none;
        min-width: 250px;
        min-height: 50px;
        background: linear-gradient(90deg,
                rgba(129, 230, 217, 1) 0%,
                rgba(79, 209, 197, 1) 100%);
        border-radius: 1000px;
        color: darkslategray;
        cursor: pointer;
        box-shadow: 10px 8px 22px rgba(79, 209, 197, 0.64);
        font-weight: 700;
        transition: 0.3s;
    }
    .w-btn-neon2:hover {
        transform: scale(1.2);
        text-decoration-line: none;
    }

    .w-btn-neon2:hover::after {
        content: "";
        width: 30px;
        height: 30px;
        border-radius: 100%;
        border: 6px solid #00ffcb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }

    .w-btn-neon22 {
        display: inline-block;
        position: relative;
        border: none;
        min-width: 100px;
        min-height: 50px;
        background: linear-gradient(90deg,
                rgba(129, 230, 217, 1) 0%,
                rgba(79, 209, 197, 1) 100%);
        border-radius: 1000px;
        color: darkslategray;
        cursor: pointer;
        box-shadow: 10px 8px 22px rgba(79, 209, 197, 0.64);
        font-weight: 700;
        transition: 0.3s;
    }
    .w-btn-neon22:hover {
        transform: scale(1.2);
        text-decoration-line: none;
        
    }

    .w-btn-neon22:hover::after {
        content: "";
        width: 30px;
        height: 30px;
        border-radius: 100%;
        border: 6px solid #00ffcb;
        position: absolute;
        z-index: -1;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        animation: ring 1.5s infinite;
    }
    .img_link:hover {
        transition: all;
        transition-duration: 0.7s;
        transform: scale(1.2);
        box-shadow: 0 0 80px rgb(69, 69, 69);
        border-radius: 3%;
    }
</style>
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}

<div class="container" id="top">
    <h1> &#128248; Photo</h1>

    <div class="album_title_list">
        <ul>
            {% for object in object_list %}
            <li class="on">
                <a class="w-btn-neon2 p-3 px-5" href="#{{ forloop.counter }}">
                    <span>{{ object }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>


    {% for object in object_list %}
    <span id="{{ forloop.counter }}"><br></span>
    <h3 class="title d-inline-block p-3"> &#128486; {{ object }} &#128487; </h3> <br>
    <span style="background-color:#fffd95">
        개봉일 : {{ object.description }}
    </span>
    <div class="thumbnail">
        {% for photo in object.photo_set.all %}
        <a href="{{ photo.get_absolute_url }}">
            <img src="{{ photo.image.url }}" alt="{{ photo }}" style="width:500px; height:300px;" class="img_link"></a>
        {% endfor %}
    </div>
    <hr>

    {% endfor %}
    <div id="bottom"></div>
    <div style="position: fixed; bottom: 40px; right: 40px;">
        <a href="#top_" class="w-btn-neon22 p-2 px-5">top</a><br><br>
        <a href="#bottom" class="w-btn-neon22 p-2 px-5">bottom</a>
        
    </div>
</div>

{% endblock %}
<!-- 콘텐츠 블록 End -->

Oda/photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Change Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Photo Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
            <tr class="table-info">
                <th>Album</th>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.album }}</td>
                <td>{{ item.title }}</td>
                <td>{{ item.description }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
                <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
    </div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Delete Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Photo Delete</h1>
    <br>
    
    <form method="post"> {% csrf_token %}
        <p>이미지 "{{ object }}"을/를 진심으로 삭제하는건가요?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/photo/templates/photo/photo_detail.html
{% extends 'base.html'%}

<!-- 제목 블럭 Start (기본값 My Blog Page) -->
{% block title %}
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록  Start -->
{% block extra-style%}

{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    {{object}}<br>
    <img src="{{ photo.image.url }}" style="width:1200px; height:700px;">
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

Oda/photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Photo Add Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
<h1>Photo Create/Update - {{ user }}</h1>
<p class="font-italic">사진 업로드 또는 수정을 진행할 수 있습니다.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

{% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" class="card pt-3">
{% else %}
    <form method="post" class="card pt-3">
{% endif %}
        {% csrf_token %}

        <div class="form-group row">
            {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-2">
                {{ form.album|add_class:"form-control" }}
            </div>
            <div class="col-sm-2 my-auto">
                <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">
                    Add Album</a>
            </div>
        </div>

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.image|add_class:"form-control-file" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.description|add_class:"form-control"|attr:"rows:3" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>

    </form>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->