Oda/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    # 예시 : blog/
    path('', views.PostLV.as_view(), name='index'),

    # 예시 : blog/post/ (same as /blog/)
    path('post/', views.PostLV.as_view(), name='post_list'),

    # 예시 : blog/post/django-example/슬러그-슬러그-슬러그
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name = 'post_detail'),

    # 예시 : blog/archive/
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    
    # 예시 : blog/archive/2022/
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),

    # 예시 : blog/archive/2022/9월
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    # 예시 : blog/archive/2022/9월/16/
    path('archive/<int:year>/<str:month>/<int:day>', views.PostDAV.as_view(), name='post_day_archive'),

    # 예시 : blog/archive/today/
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    # Example : /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),

    # Example : /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),


    path('add/', views.PostCreateView.as_view(), name='add'),
    path('change/', views.PostChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete'),
]

Oda/bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
    
]

Oda/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import BookmarkLV, BookmarkDV
from mysite import views
from django.conf.urls.static import static
from django.conf import settings
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register', views.UserCreateView.as_view(), name='register'),
    path('accounts/register/done', views.UserCreateDoneTV.as_view(), name='register_done'),

    # shkim
    path('', views.HomeView.as_view(), name='home'), # 추가

    path('bookmbark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
    path('market/', include('market.urls')),

    # path('bookmark/', BookmarkLV.as_view(), name='index'),
    # path('bookmark/<int:pk>', BookmarkDV.as_view(), name='detail'),


] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Oda/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique = True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

Oda/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark  # [주의]
from django.views.generic import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

# Create your views here.
class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark

# LoginRequiredMixin -> 로그인한 사용자가 아니면 로그인 페이지로 이동
class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
# LoginRequiredMixin -> 로그인한 사용자가 아니면 로그인 페이지로 이동
# object_list -> 현재 로그인한 사용자가 작성한 Bookmark
class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmark/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner = self.request.user)

# OwnerONLY Mixin -> 작성자만이 수정할 수 있도록
class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

# OwnerOnlyMixin -> 작성자만이 삭제할 수 있도록
class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

Oda/bookmark/templates/bookmark/bookmark_change_list.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Change List Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
<div class="container">
    <h1>Bookmark Change - {{ user }}</h1>
    <br>

    <table class="table table-bordered table-condensed table-striped">
        <thead>
            <tr class="table-primary">
                <th>Title</th>
                <th>Url</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            {% for item in object_list %}
            <tr>
                <td>{{ item.title }}</td>
                <td>{{ item.url }}</td>
                <td>{{ item.owner }}</td>
                <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
                <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Delete Confirm Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        <p>"{{ object }}"를 진짜 삭제하시겠습니까? 이 작업은 돌이킬 수 없습니다. </p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}

{% block title %}bookmark_detail.html{% endblock %}

{% block content %}
<h1>{{ object.title }}</h1>
<ul>
    <li>
        <a href="{{ object.url }}">{{ object.url }}</a>
    </li>
</ul>
{% endblock %}


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookmark_Detail</title>
</head>
<body>
    <h1>북마크 디테일</h1>
    <ul>
        <li>
            <a href="{{ object.url }}">{{ object.url }}</a>
        </li>
    </ul>
</body>
</html> {% endcomment %}

Oda/bookmark/templates/bookmark/bookmark_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

<!-- 제목 블록 Start (기본값 My Blog Page) -->
{% block title %}
My Blog Bookmark Form Page Page
{% endblock %}
<!-- 제목 블록 End -->

<!-- 스타일 블록 Start -->
{% block extra-style %}
{% endblock %}
<!-- 스타일 블록 End -->

<!-- 콘텐츠 블록 Start -->
{% block content %}
    <h1>Bookmark Create/Update - {{ user }}</h1>
    <p class="font-italic">북마크를 생성하거나 수정을 할 수 있습니다.</p>
    
    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}
    
    <form method="post" class="card pt-3"> {% csrf_token %}
    
        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>
    
        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>
    
        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info" />
            </div>
        </div>
    </form>
{% endblock %}
<!-- 콘텐츠 블록 End -->

<!-- 스크립트 블록 Start -->
{% block extra-script %}

{% endblock %}
<!-- 스크립트 블록 End -->

Oda/bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}

{% block title %}bookmark_list.html{% endblock %}

{% block extra-style %}
<style type="text/css">
    
</style>
{% endblock %}

{% block content %}

{% if user.is_active %}
    <a href="btn btn-outline-dark" href="{% url 'bookmark:add' %}">글쓰기</a>
    <a href="btn btn-outline-dark" href="{% url 'bookmark:change' %}">내 글보기</a>
    
{% endif %}

<h1>Bookmark List</h1>
<ul>
    {% for bm in object_list %}
    <li>
        <a href="{% url 'bookmark:detail' bm.id %}">{{ bm }}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}


{% comment %} <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookmark_List</title>
</head>
<body>
    <h1>북마크 리스트</h1>
    <ul>
        {% for bm in object_list %}
        <li>
            <a href="{% url 'bookmark:detail' bm.id %}">{{ bm }}</a>
        </li>
        {% endfor %}
    </ul>
</body>
</html> {% endcomment %}